[project]
name = "lidosc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pybooklid>=1.0.0",
    "python-osc>=1.9.3",
]
